apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogql
spec:
  selector:
    matchLabels:
      app: blogql
  replicas: 1
  template:
    metadata:
      name: blogql
      labels:
        app: blogql
    spec:
      containers:
        - name: blogql
          image: "snoopdave/blogql:latest"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              cpu: "200m"
              memory: "200Mi"
          ports:
            - containerPort: 4000
          env:
            - name: APOLLO_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apollo.keySecretName }}
                  key: apolloKey
            - name: APOLLO_GRAPH_REF
              value: {{ .Values.apollo.graphRef }}
            - name: APOLLO_SCHEMA_REPORTING
              value: "{{ .Values.apollo.schemaReporting }}"



