---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogql
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/preserve-host: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    certmanager.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.blogQlHost}}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.blogQlHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blogql
                port:
                  number: 80
