apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogql-client
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/preserve-host: "true"
spec:
  rules:
    - host: {{ .Values.ingress.blogQlClient }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blogql-client
                port:
                  number: 80
