apiVersion: v1
kind: Service
metadata:
  name: blogql-client
  labels:
    app: blogql-client
spec:
  selector:
    app: blogql-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
