name: build-test

on:
  workflow_call:

jobs:

  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    # checkout project  code
    - uses: actions/checkout@v3

    # setup node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: ./server/yarn.lock

    # install dependencies and build server
    - run: |
        yarn install
        yarn run build
      working-directory: server

    # install dependencies and build client
    - run: |
        yarn install
        yarn run build
      working-directory: client
