name: docker-build

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
      tags:
        required: true
        type: string
    secrets:
      docker-username:
        required: true
        type: string
      docker-password:
        required: true
        type: string

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
