name: publish-schema

# Publish GraphQL schema to Apollo Studio

on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string
      schema-path:
        required: true
        type: string
      graph-ref:
        required: true
        type: string
    secrets:
      ROVER_API_KEY:
        required: true
      #APOLLO_REGISTRY_URL:
        #required: true

jobs:

  check:
    runs-on: ubuntu-latest

    env:
      APOLLO_KEY: ${{ secrets.ROVER_API_KEY }}
      APOLLO_GRAPH_REF: ${{ inputs.graph-ref }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
      #APOLLO_REGISTRY_URL: ${{ secrets.APOLLO_REGISTRY_URL }} # needed if not running against prod Studio

    steps:
      # Checkout project code
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.9.1 | sh
          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish schema
        run: |
          rover graph publish ${APOLLO_GRAPH_REF} --schema ${{ inputs.schema-path }}
        working-directory: ${{ inputs.working-dir }}

