# Copyright David M. Johnson (snoopdave@gmail.com).
# Licensed under Apache Software License v2.

name: build-test

on:
  workflow_call:
    secrets:
      CHROMATIC_PROJECT_TOKEN:
        required: true
jobs:

  build-test:
    runs-on: ubuntu-latest

    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: ./server/yarn.lock

    - name: Build and test server
      run: |
        yarn install
        yarn build
        yarn test
      working-directory: server

    # install dependencies, build and test client
    - name: Build and test client
      run: |
        cat > src/googlecid.ts << EOF
        export const GOOGLE_SIGNON_CID='dummy';
        EOF
        yarn install
        yarn build
        yarn test
      working-directory: client

    - name: Run Chromatic publish and check
      uses: chromaui/action@v1
      with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        workingDir: client
