# Copyright David M. Johnson (snoopdave@gmail.com).
# Licensed under Apache Software License v2.

name: docker-build

# Runs docker build in top-level directory

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
      push: # true will cause push to Docker hub
        required: true
        type: boolean
      tags:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.dir }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
