apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogql-server
spec:
  selector:
    matchLabels:
      app: blogq-server
  replicas: 1
  template:
    metadata:
      name: blogql-server
      labels:
        app: blogql-server
    spec:
      containers:
        - name: blogql-server
          image: "snoopdave/blogql-server:latest"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              cpu: "200m"
              memory: "200Mi"
          ports:
            - containerPort: 4000
          env:
            - name: APOLLO_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apollo.keySecretName }}
                  key: apolloKey
            - name: APOLLO_GRAPH_REF
              value: {{ .Values.apollo.graphRef }}
            - name: APOLLO_SCHEMA_REPORTING
              value: "{{ .Values.apollo.schemaReporting }}"



